# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_printers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tft',
            new_name='Panel_printers',
        ),
    ]
