# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandTft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=75)),
            ],
            options={
                'ordering': ('brand',),
            },
        ),
        migrations.CreateModel(
            name='InterfaceTft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(max_length=75)),
            ],
            options={
                'ordering': ('interface',),
            },
        ),
        migrations.CreateModel(
            name='ResolutionTft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(max_length=75)),
                ('resolution_x', models.IntegerField()),
                ('resolution_y', models.IntegerField()),
            ],
            options={
                'ordering': ('resolution_x', 'resolution_y'),
            },
        ),
        migrations.CreateModel(
            name='SizeTft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_inch', models.FloatField()),
            ],
            options={
                'ordering': ('size_inch',),
            },
        ),
        migrations.CreateModel(
            name='Tft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opto_part_number', models.CharField(max_length=11)),
                ('panel_model', models.CharField(max_length=100)),
                ('brightness', models.IntegerField()),
                ('contrast', models.CharField(max_length=75)),
                ('colors', models.CharField(max_length=75)),
                ('backlight', models.CharField(max_length=75)),
                ('viewing_angle_upper', models.IntegerField()),
                ('viewing_angle_down', models.IntegerField()),
                ('viewing_angle_left', models.IntegerField()),
                ('viewing_angle_right', models.IntegerField()),
                ('outline_x', models.FloatField()),
                ('outline_y', models.FloatField()),
                ('outline_z', models.FloatField()),
                ('active_area_x', models.FloatField()),
                ('active_area_y', models.FloatField()),
                ('temperature_operating_min', models.FloatField()),
                ('temperature_operating_max', models.FloatField()),
                ('temperature_storage_min', models.FloatField()),
                ('temperature_storage_max', models.FloatField()),
                ('production', models.BooleanField(default=True)),
                ('touch_panel', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_tft', to='tft.BrandTft')),
                ('interfaces', models.ManyToManyField(related_name='interface_tft', to='tft.InterfaceTft')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_tft', to='tft.ResolutionTft')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_tft', to='tft.SizeTft')),
            ],
            options={
                'ordering': ('size',),
            },
        ),
    ]
