# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tft',
            name='description',
            field=models.CharField(default='This is a TFT display that will suprise you!', max_length=500),
            preserve_default=False,
        ),
    ]
