# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0002_tft_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolutiontft',
            name='primary_colors',
            field=models.CharField(default='RGB', max_length=3),
        ),
        migrations.AddField(
            model_name='resolutiontft',
            name='ratio',
            field=models.CharField(default='4/3', max_length=30),
            preserve_default=False,
        ),
    ]
