# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0004_auto_20160616_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandtft',
            name='brand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='partners.Partner'),
        ),
    ]
