# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('logo', models.FileField(upload_to='')),
                ('area', models.ManyToManyField(related_name='business_area_partner', to='partners.BusinessArea')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
