# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20160712_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(upload_to='static/media/partners/logos/'),
        ),
    ]
