# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_auto_20160712_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessarea',
            name='weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(upload_to=''),
        ),
    ]
