# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainShowcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_transition', models.CharField(default='fade', max_length=50)),
                ('background_image', models.ImageField(default="{% static 'media/img/slides/slide-bg.jpg' %}", upload_to='')),
                ('alternate_text', models.CharField(default='photo', max_length=50)),
                ('data_bgposition', models.CharField(default='center center', max_length=100)),
                ('data_bgfit', models.CharField(default='cover', max_length=100)),
                ('data_bgrepeat', models.CharField(default='no-repeat', max_length=100)),
                ('slide_class', models.CharField(default='rev-slidebg', max_length=100)),
                ('cpt_lft_class', models.CharField(default='tp-caption', max_length=100)),
                ('cpt_lft_pos_x', models.IntegerField(default=177)),
                ('cpt_lft_pos_y', models.IntegerField(default=180)),
                ('cpt_lft_transform', models.CharField(default='x:[-300%];opacity:0;s:500;', max_length=100)),
                ('cpt_rgt_class', models.CharField(default='tp-caption', max_length=100)),
                ('cpt_rgt_pos_x', models.IntegerField(default='480')),
                ('cpt_rgt_pos_y', models.IntegerField(default='180')),
                ('cpt_transform_rgt', models.CharField(default='x:[300%];opacity:0;s:500;', max_length=100)),
                ('cpt_data_start', models.IntegerField(default=1000)),
                ('cpt_img', models.ImageField(default="{% static 'media/img/slides/slide-title-border.png' %}", upload_to='')),
                ('cpt_img_alt', models.CharField(default='dash picture', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MainShowcaseLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryShowcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_1', models.CharField(max_length=100, verbose_name='Titre 1')),
                ('background_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
