# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainshowcase',
            name='background_image',
            field=models.ImageField(upload_to='static/media/showcase/'),
        ),
    ]
