# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_auto_20160531_1325'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainShowcaseSlide',
        ),
        migrations.DeleteModel(
            name='MainShowcaseSlideLayer',
        ),
    ]
