# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='interest',
            field=models.ManyToManyField(to='partners.BusinessArea'),
        ),
    ]
