# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opto_part_number', models.CharField(max_length=11)),
            ],
        ),
    ]
